//
// Created by wangq on 2019/3/29.
//

#ifndef DEMO4ANY_COM_WANG_DEMO4ANY_JNI_NATIVEWRAPPER_H
#define DEMO4ANY_COM_WANG_DEMO4ANY_JNI_NATIVEWRAPPER_H

#endif //DEMO4ANY_COM_WANG_DEMO4ANY_JNI_NATIVEWRAPPER_H
